//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CC8_MVC_Prj.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductsTable
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public float Price { get; set; }
        public int Quantity { get; set; }
        public Nullable<int> Sales_SaleId { get; set; }
    
        public virtual Sale Sale { get; set; }
    }
}
